spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointmentdb
    username: postgres
    password: root

#cron:
#  expression: '*/1 * * * *'

logging:
#  file:
#    path: logs
#    name: logs.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
      max-file-size: 10MB
      max-history: 1000
  level:
#    org:
#      springframework:
#        security: TRACE
#
#cloud:
#  aws:
#    region:
#      static: us-east-1
#      auto: true
#
#custom:
#  bucket-name: bockett
